### ISSUE TITLE
six modules removed during cleanup

### ISSUE THREAD

**Issue by keppo070** [linuxserver/docker-nzbget#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Apprise would work from NZBGET. Notify script visible in settings NZBGET

## Current Behavior
Module six is removed
https://github.com/linuxserver/docker-nzbget/blob/master/Dockerfile#L96

## Steps to Reproduce

1. docker exec -it nzbget /bin/bash
2. python Notify.py
3.
4.

## Environment
**OS:** Debian 10.6
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DOCKER_MODS=linuxserver/mods:universal-apprise
    volumes:
      - /home/<userid>/docker-config/nzbget/config:/config
      - /mnt/storage/tempdata/complete:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
NZBGet: https://nzbget.net/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO] nzbget 21.0 server-mode
[INFO] Reloading...
[INFO] nzbget 21.0 server-mode
[INFO] Executing script Notify.py with command TestServers
[INFO] Notify: Traceback (most recent call last):
[INFO] Notify:   File "/downloads/scripts/Notify.py", line 169, in <module>
[INFO] Notify:     import six
[INFO] Notify: ModuleNotFoundError: No module named 'six'
[ERROR] Script Notify.py with command TestServers failed (terminated with unknown status)
```
