### ISSUE TITLE
Massive performance degradation

### ISSUE THREAD

**Issue by worldofgeese** [linuxserver/docker-nzbget#118]
------------------------------

## Expected Behavior
Server minimally affected by nzbget container.

## Current Behavior
As of the beginning of last week, the nzbget container causes huge performance loss in network connectivity to my server. SSH and other containers which depend on network bandwidth slow to a crawl. To test for the offending container, I tore my docker-compose.yml down to a minimum of containers and added a container back each day and observed the results. After 4 days and 4 containers, I put up NZBGet and can see a clear correlation between it and ssh access times over one minute, other containers like Synapse timing out, etc.

## Steps to Reproduce
1. Run NZBGet latest tag.
2. Observe over the next few hours as your server shits the bed.

## Environment
**OS:**
Synology DSM 6.2
**CPU architecture:** x86_64/arm32/arm64
x86_64
**How docker service was installed:**
DSM provided.

## Command used to create docker container (run/create/compose/screenshot)
```
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    hostname: nzbget
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "6789:6789"
    volumes:
      - $USERDIR/docker/nzbget/config:/config
      - $USERDIR/downloads:/downloads
      - $USERDIR/docker/nzbget/intermediate:/intermediate
    environment:
      PUID: 1037
      PGID: ${PGID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nzbget-rtr.entrypoints=https"
      - "traefik.http.routers.nzbget-rtr.rule=Host(`nzbget.$DOMAINNAME`)"
      - "traefik.http.routers.nzbget-rtr.tls=true"
      - "traefik.http.routers.nzbget-rtr.tls.certresolver=default"
      ## HTTP Services
      - "traefik.http.routers.nzbget-rtr.service=nzbget-svc"
      - "traefik.http.services.nzbget-svc.loadbalancer.server.port=6789"
```

## Docker logs
Logs attached.
[nzbget.log](https://github.com/linuxserver/docker-nzbget/files/5451223/nzbget.log)
