### ISSUE TITLE
Ability to set username / password from environmental variables

### ISSUE THREAD

**Issue by khromov** [linuxserver/docker-nzbget#128]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
It would be useful if you could specify a username and password for the basic authentication using environmental variables instead of having them be hard-coded. Optionally this could also be enforced on container startup, but it's not a hard requirement imho.

Example:

```yaml
 nzbget: 
    image: ghcr.io/linuxserver/nzbget
    # ...
    environment:
      - USER=myuser
      - PASSWORD=supersecretpassword
      # ...
    # ...
```

Or these env vars could be fetched via `env_file`

## Current Behavior
Not possible to set username/password.

## Alternatives Considered
Just changing the default login/password as per the instructions. 😄
It works, but automation ftw!
