### ISSUE TITLE
Can't run docker container, unable to find libraries

### ISSUE THREAD

**Issue by chriscn** [linuxserver/docker-nzbget#147]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. Unable to run the docker container, have tried reinstalling multiple times. Clearing the image. deleting the folders etc

## Environment
**OS:** Ubuntu 22.04 LTS
**CPU architecture:** x86_64/arm32/arm64 64 Bit
**How docker service was installed:** Using aptitude

## Command used to create docker container (run/create/compose/screenshot)
```yaml
nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/appdata/nzbget:/config
      - /var/downloads:/downloads
    restart: unless-stopped
```

## Docker logs
[NZBget log](https://www.toptal.com/developers/hastebin/zohugazufa.sql)
