### ISSUE TITLE
Unrar: Input/output error

### ISSUE THREAD

**Issue by iDVB** [linuxserver/docker-nzbget#46]
Frequently failing postprocessing during unrar. (80-90%)
They all show the same log error...
```
Unpack for the_longish_file_name.cp(tt0458525) failed
Unrar error code: 2
Unrar: Program aborted
Unrar: Input/output error
```
![image](https://user-images.githubusercontent.com/189506/34970388-266ab174-fa42-11e7-9db0-c36e077afa08.png)

Windows 10
Docker Version 17.12.0-ce-win47 (15139)

`docker-compose up`
```
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - ./opt/appdata/nzbget/config:/config
      - e:/downloads:/downloads
    ports:
      - 27020:6789
    restart: always
```
