### ISSUE TITLE
Could not resolve hostname localhost

### ISSUE THREAD

**Issue by rspenc29** [linuxserver/docker-nzbget#57]
I recently upgraded my docker image and now I can't download any nzb files from my `linuxserver/hydra2` container. I get the following error...

    [ERROR] Could not resolve hostname localhost: ErrNo -2, Name or service not known

Everything was working fine until a recent upgrade. I didn't change any configurations.

I can ping localhost just fine within the nzbget container. Just seems nzbget is having issues.

Both containers are using host networking.

Here is the relevant `docker-compose.yml`

```
version: '3.6'
services:
    nzbget:
        image: linuxserver/nzbget
        restart: unless-stopped
        container_name: nzbget
        network_mode: host
        volumes:
            - /appdata/downloads:/downloads
            - /appdata/nzbget:/config
        environment:
            - TZ=America/New_York
            - PUID=99
            - PGID=100
    hydra:
        image: linuxserver/hydra2
        restart: unless-stopped
        container_name: hydra2
        network_mode: host
        volumes:
            - /appdata/hydra2:/config
            - /appdata/downloads/nzb:/downloads
        environment:
            - TZ=America/New_York
            - PGID=100
            - PUID=99
```
