### ISSUE TITLE
Can't stop the container, can't kill it, can't rm it

### ISSUE THREAD

**Issue by leonroy** [linuxserver/docker-nzbget#70]
Having lots of reliability issues with the nzbget container.

Host OS: Ubuntu 18.04 LTS
Create: docker-compose up -d
Conf:
```
version: "2"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/nzbget:/config
      - /mnt/downloads/Usenet:/downloads
    ports:
      - 6790:6789
    restart: unless-stopped
```

Log output below.

Volume is running over cifs mounted in host.

When running `docker-compose kill`:

```
compose.parallel.feed_queue: Pending: {<Container: nzbget (ad702b)>}
compose.parallel.feed_queue: Starting producer thread for <Container: nzbget (ad702b)>
compose.cli.verbose_proxy.proxy_callable: docker kill <- ('ad702b6a12fc17dfedafcd2379aa72a329a202263d327e4b6c42aac851cb5985', signal=None)

compose.parallel.feed_queue: Pending: set()
...
...
compose.parallel.parallel_execute_iter: Failed: <Container: nzbget (ad702b)>
compose.parallel.feed_queue: Pending: set()

ERROR: for nzbget  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: compose.cli.errors.log_timeout_error: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

I cannot stop/start/rm or destroy the container in any way.

NZBget also behaves unreliably.

Any thoughts appreciated.
