### ISSUE TITLE
chown as abc:abc causing permission issues, why does this exist?

### ISSUE THREAD

**Issue by adrkable** [linuxserver/docker-nzbget#94]
https://github.com/linuxserver/docker-nzbget/blob/a8652945160207f55b77fe619f8f6b5b67d9d8d1/root/etc/cont-init.d/30-config#L14

Can anyone shed light on these permissions and why the exist?  Seems to be causing ownership conflicts.

```
$ sudo docker-compose logs nzbget
Attaching to nzbget
nzbget        | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
nzbget        | [s6-init] ensuring user provided files have correct perms...exited 0.
nzbget        | [fix-attrs.d] applying ownership & permissions fixes...
nzbget        | [fix-attrs.d] done.
nzbget        | [cont-init.d] executing container initialization scripts...
nzbget        | [cont-init.d] 01-envfile: executing... 
nzbget        | [cont-init.d] 01-envfile: exited 0.
nzbget        | [cont-init.d] 10-adduser: executing... 
nzbget        | 
nzbget        | -------------------------------------
nzbget        |           _         ()
nzbget        |          | |  ___   _    __
nzbget        |          | | / __| | |  /  \ 
nzbget        |          | | \__ \ | | | () |
nzbget        |          |_| |___/ |_|  \__/
nzbget        | 
nzbget        | 
nzbget        | Brought to you by linuxserver.io
nzbget        | We gratefully accept donations at:
nzbget        | https://www.linuxserver.io/donate/
nzbget        | -------------------------------------
nzbget        | GID/UID
nzbget        | -------------------------------------
nzbget        | 
nzbget        | User uid:    1000
nzbget        | User gid:    1000
nzbget        | -------------------------------------
nzbget        | 
nzbget        | chown: changing ownership of '/config': Operation not permitted
nzbget        | [cont-init.d] 10-adduser: exited 0.
nzbget        | [cont-init.d] 30-config: executing... 
nzbget        | chown: changing ownership of '/downloads': Operation not permitted
nzbget        | chown: changing ownership of '/config/nzbget.conf': Operation not permitted
nzbget        | chown: changing ownership of '/config': Operation not permitted
nzbget        | [cont-init.d] 30-config: exited 0.
nzbget        | [cont-init.d] 99-custom-files: executing... 
nzbget        | [custom-init] no custom files found exiting...
nzbget        | [cont-init.d] 99-custom-files: exited 0.
nzbget        | [cont-init.d] done.
nzbget        | [services.d] starting services
nzbget        | [services.d] done.
nzbget        | [INFO] nzbget 21.0 server-mode
```

**docker-compose.yaml**
```
version: "2"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - nzbget-data:/config:nocopy
      - downloads-data:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

volumes:
   nzbget-data:
      driver: nfs
      driver_opts:
        share: "synology.lan:/volume4/AppDir/docker/nzbget"
   downloads-data:
      driver: nfs
      driver_opts:
        share: "synology.lan:/volume2/Downloads"

```
